# Render Blueprint for Agri-Drone Accounts System
services:
  # Backend API Service
  - type: web
    name: agri-drone-accounts-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start

    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: agri-drone-accounts-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://agri-drone-accounts-api.onrender.com/api
